conan remove qt_all/0.1@issue/testing -f
conan create output/qt_all/conanfile.py issue/testing
conan remove qtbase/0.1@issue/testing -f
conan create output/qtbase/conanfile.py issue/testing
conan remove qtsvg/0.1@issue/testing -f
conan create output/qtsvg/conanfile.py issue/testing
conan remove qtdeclarative/0.1@issue/testing -f
conan create output/qtdeclarative/conanfile.py issue/testing
conan remove qtactiveqt/0.1@issue/testing -f
conan create output/qtactiveqt/conanfile.py issue/testing
conan remove qtscript/0.1@issue/testing -f
conan create output/qtscript/conanfile.py issue/testing
conan remove qtmultimedia/0.1@issue/testing -f
conan create output/qtmultimedia/conanfile.py issue/testing
conan remove qttools/0.1@issue/testing -f
conan create output/qttools/conanfile.py issue/testing
conan remove qtxmlpatterns/0.1@issue/testing -f
conan create output/qtxmlpatterns/conanfile.py issue/testing
conan remove qttranslations/0.1@issue/testing -f
conan create output/qttranslations/conanfile.py issue/testing
conan remove qtdoc/0.1@issue/testing -f
conan create output/qtdoc/conanfile.py issue/testing
conan remove qtrepotools/0.1@issue/testing -f
conan create output/qtrepotools/conanfile.py issue/testing
conan remove qtqa/0.1@issue/testing -f
conan create output/qtqa/conanfile.py issue/testing
conan remove qtlocation/0.1@issue/testing -f
conan create output/qtlocation/conanfile.py issue/testing
conan remove qtsensors/0.1@issue/testing -f
conan create output/qtsensors/conanfile.py issue/testing
conan remove qtconnectivity/0.1@issue/testing -f
conan create output/qtconnectivity/conanfile.py issue/testing
conan remove qtwayland/0.1@issue/testing -f
conan create output/qtwayland/conanfile.py issue/testing
conan remove qt3d/0.1@issue/testing -f
conan create output/qt3d/conanfile.py issue/testing
conan remove qtimageformats/0.1@issue/testing -f
conan create output/qtimageformats/conanfile.py issue/testing
conan remove qtgraphicaleffects/0.1@issue/testing -f
conan create output/qtgraphicaleffects/conanfile.py issue/testing
conan remove qtquickcontrols/0.1@issue/testing -f
conan create output/qtquickcontrols/conanfile.py issue/testing
conan remove qtserialbus/0.1@issue/testing -f
conan create output/qtserialbus/conanfile.py issue/testing
conan remove qtserialport/0.1@issue/testing -f
conan create output/qtserialport/conanfile.py issue/testing
conan remove qtx11extras/0.1@issue/testing -f
conan create output/qtx11extras/conanfile.py issue/testing
conan remove qtmacextras/0.1@issue/testing -f
conan create output/qtmacextras/conanfile.py issue/testing
conan remove qtwinextras/0.1@issue/testing -f
conan create output/qtwinextras/conanfile.py issue/testing
conan remove qtandroidextras/0.1@issue/testing -f
conan create output/qtandroidextras/conanfile.py issue/testing
conan remove qtwebsockets/0.1@issue/testing -f
conan create output/qtwebsockets/conanfile.py issue/testing
conan remove qtwebchannel/0.1@issue/testing -f
conan create output/qtwebchannel/conanfile.py issue/testing
conan remove qtwebengine/0.1@issue/testing -f
conan create output/qtwebengine/conanfile.py issue/testing
conan remove qtcanvas3d/0.1@issue/testing -f
conan create output/qtcanvas3d/conanfile.py issue/testing
conan remove qtwebview/0.1@issue/testing -f
conan create output/qtwebview/conanfile.py issue/testing
conan remove qtquickcontrols2/0.1@issue/testing -f
conan create output/qtquickcontrols2/conanfile.py issue/testing
conan remove qtpurchasing/0.1@issue/testing -f
conan create output/qtpurchasing/conanfile.py issue/testing
conan remove qtcharts/0.1@issue/testing -f
conan create output/qtcharts/conanfile.py issue/testing
conan remove qtdatavis3d/0.1@issue/testing -f
conan create output/qtdatavis3d/conanfile.py issue/testing
conan remove qtvirtualkeyboard/0.1@issue/testing -f
conan create output/qtvirtualkeyboard/conanfile.py issue/testing
conan remove qtgamepad/0.1@issue/testing -f
conan create output/qtgamepad/conanfile.py issue/testing
conan remove qtscxml/0.1@issue/testing -f
conan create output/qtscxml/conanfile.py issue/testing
conan remove qtspeech/0.1@issue/testing -f
conan create output/qtspeech/conanfile.py issue/testing
conan remove qtnetworkauth/0.1@issue/testing -f
conan create output/qtnetworkauth/conanfile.py issue/testing
conan remove qtremoteobjects/0.1@issue/testing -f
conan create output/qtremoteobjects/conanfile.py issue/testing
conan remove qtwebglplugin/0.1@issue/testing -f
conan create output/qtwebglplugin/conanfile.py issue/testing
conan remove qt/0.1@issue/testing -f
conan create output/qt/conanfile.py issue/testing
